/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.nh;

import net.nh.entity.Customer;
import net.nh.repository.CustomerRepository;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class CustomerRepositoryTest extends MongoRepositoryTestBase {

    @Autowired
    public CustomerRepository repository;

    @Test
    public void testInsertAndRetrieve() {
        Customer c = new Customer(2L, "Joe", "Bloggs", "ah209", "73t48rt3gfvh");
        repository.insert(c);

        Optional<Customer> byId = repository.findById(c.getId());
        assertTrue("Could not find customer by id", byId.isPresent());
    }

    @Test
    public void testInsertMultipleAndRetrieve() {
        Customer c1 = new Customer(1L, "Joe", "Bloggs", "ah209", "73t48rt3gfvh");
        repository.insert(c1);

        Customer c2 = new Customer(2L, "James", "Smith", "js20", "98237yrb23");
        repository.insert(c2);

        List<Customer> expectedResults = Arrays.asList(c1, c2);

        List<Customer> actualResults = repository.findAll();
        assertEquals("Incorrect number of results returned", 2, actualResults.size());

        actualResults.sort(Comparator.comparing(Customer::getId));
        assertEquals("Database contents not as expected", expectedResults, actualResults);
    }

}
